### ISSUE TITLE
Update msgs/chats list

### ISSUE THREAD

**Issue by Yodzorah** [paul-nameless/tg#130] opened 2020-07-12 05:28 UTC
# Messages

1. Write a message `ABC`.
-> The message is shown as expected.

2. Edit it to make it `XYZ`.
-> The message is still displayed as `ABC`, until `tg` is restarted.

Expected result: the edited message should display the new content right after the edit was finished.

# Chats list

1. Open `tg`.
-> You have `N` chats.

2. Join a group.
-> You still have `N` chats, until `tg` is restarted.

Expected result: `N+1` chats, display the new group in the chats list right after the user has joined.

**Comment by paul-nameless** [comment] 2020-07-13 05:24
Patch which will show new chats is in master now, so new groups will appear.
About edited message, I can't reproduce. Is it happening every time?

**Comment by lightme16** [comment] 2020-07-13 06:29
I also noticed issue with msg editing. It is reproducing only for last msg in the chat for me. However, there are no problems with editing some older message. I think it is a recent but, because it used to work correctly.

**Comment by paul-nameless** [comment] 2020-07-15 06:12
Can't reproduce the issue with edited msg. Closing for now.

**Closed by paul-nameless** 2020-07-15 06:12 UTC
Labels: bug
