### ISSUE TITLE
Cyryllic symbols aren't being shown

### ISSUE THREAD

**Issue by asm0dey** [paul-nameless/tg#84] opened 2020-06-21 07:25 UTC
For me it's how tg looks:

![image](https://user-images.githubusercontent.com/1297282/85219093-79a62d00-b3a9-11ea-9a7b-187066966b05.png)

**Comment by paul-nameless** [comment] 2020-06-21 10:16
Helllo, what terminal emulator are you using? Is it reproduced in other terminals?
I need a little bit more info to help you, cause mine shows cyryllic fine.

**Comment by asm0dey** [comment] 2020-06-21 10:19
Konsole, have the same reproduced in xterm and uxterm.

**Comment by lightme16** [comment] 2020-06-21 18:57
Me also have no problems with cyrillic characters. In general can you see cyrillic characters in your terminal when using other apps? How did you install this app? Docker, pypi or sources?  
![image](https://user-images.githubusercontent.com/9078927/85232704-af7afe00-b409-11ea-9d64-369b62ef09ed.png)

**Comment by asm0dey** [comment] 2020-06-22 06:00
I have the roblem fixed. Somehow I had locale set to myv_RU. After changing to en_US it works fine for me.

**Comment by paul-nameless** [comment] 2020-06-22 13:48
Good to know, glad it's resolved!
Could you please send your local setting to reproduce the issue? I would like to make a fix if possible for future versions.

**Comment by asm0dey** [comment] 2020-06-22 14:13
Didn't work for me when it was 'myv_RU.UTF-8'

**Comment by paul-nameless** [comment] 2020-06-24 01:33
I couldn't reproduce exactly this issue, so closing for now.

**Closed by paul-nameless** 2020-06-24 01:33 UTC
